# Generated by Django 6.0.4 on 2026-04-23 16:48

import wbr_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbr_media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaasset',
            name='height',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='width',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(blank=True, help_text='image, audio, video, document, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(upload_to=wbr_media.models.media_upload_path),
        ),
    ]
